config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  ID_PATTERN = /[^\/]+/ # all characters but '/'

  # login routes
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/developer/login", to: "sessions#new"
  post "auth/developer/login", to: "sessions#developer" if Rails.env.local?
  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#logout"

  # some maplibre style tries to load eg. /atm_11; catching those calls here
  get "/:map_resource" => "maps#catchall", as: :catchall, constraints: { map_resource: /[a-z]+_11/ }
  get "/m/:map_resource" => "maps#catchall", constraints: { map_resource: /[a-z]+_11/ }

  scope "/m" do
    get "", to: "maps#index", as: "maps"
    get "/", to: "maps#index"

    # map exports
    get "/:id.json" => "maps#show", constraints: { id: ID_PATTERN }, defaults: { format: "json" }
    get "/:id.geojson" => "maps#show", constraints: { id: ID_PATTERN }, defaults: { format: "geojson" }
    get "/:id.gpx" => "maps#show", constraints: { id: ID_PATTERN }, defaults: { format: "gpx" }
    get "/:id/properties" => "maps#properties", as: :map_properties, constraints: { id: ID_PATTERN }
    get "/:id" => "maps#show", as: :map, format: :html, constraints: { id: ID_PATTERN }

    post "" => "maps#create", as: :create_map
    delete "/:id" => "maps#destroy", as: :destroy_map, constraints: { id: ID_PATTERN }
  end
  get "/my" => "maps#my", as: "my"

  get "/d/:id" => "maps#show", defaults: { engine: "deck" }, as: :deck, constraints: { id: ID_PATTERN }

  get "/admin" => "admin#index"

  # map icons
  get "/icon/:public_id", to: "images#icon", as: "icon", constraints: { public_id: ID_PATTERN }
  get "/image/:public_id", to: "images#image", as: "image", constraints: { public_id: ID_PATTERN }
  post "/images", to: "images#upload", as: "upload"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "frontpage#index"
  get "/frontpage" => "frontpage#index"

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  mount Ulogger::Engine, at: "/ulogger"
end

app/models/map.rb
class Map
  include ActiveModel::Model
  include Mongoid::Document
  include Mongoid::Timestamps
  include Turbo::Broadcastable

  # mongoid callbacks: https://www.mongodb.com/docs/mongoid/current/data-modeling/callbacks/
  # broadcasts: https://www.rubydoc.info/github/hotwired/turbo-rails/Turbo/Streams/Broadcasts
  after_create do
    # using refresh to make sure map access is authorized
    broadcast_refresh_to("admin_maps_list")
    broadcast_refresh_to("public_maps_list") unless private
    # broadcast_prepend_to("admin_maps_list", target: "maps", partial: "maps/map",
    #  locals: { rw: true, avatar: true, delete: true, last_change: true })
  end
  after_destroy do
    broadcast_refresh_to("admin_maps_list")
    broadcast_refresh_to("public_maps_list") unless private
  end

  has_many :layers
  belongs_to :user, optional: true, counter_cache: true

  field :base_map, type: String, default: -> { default_base_map }
  field :center, type: Array
  field :zoom, type: String
  field :terrain, type: Boolean
  field :pitch, type: String
  field :bearing, type: String
  field :name, type: String
  field :description, type: String
  field :public_id, type: String
  field :private, type: Boolean
  field :images_count, type: Integer, default: 0

  BASE_MAPS = [ "osmRasterTiles", "satelliteTiles", "openTopoTiles" ]
  STADIA_MAPS = [ "stamenTonerTiles", "stamenWatercolorTiles" ]
  OPENFREE_MAPS = [ "openfreemapPositron", "openfreemapBright", "openfreemapLiberty" ]
  VERSATILES_MAPS = [ "versatilesColorful", "versatilesGraybeard" ]
  MAPTILER_MAPS = [ "maptilerBuildings", "maptilerHybrid", "maptilerDataviz",
                    "maptilerStreets", "maptilerNoStreets", "maptilerWinter",
                    "maptilerBike", "maptilerBasic" ]

  DEFAULT_CENTER = [ 11.077, 49.447 ].freeze
  DEFAULT_ZOOM = 12
  DEFAULT_PITCH = 30
  DEFAULT_BEARING = 0
  DEFAULT_TERRAIN = false

  after_save :broadcast_update
  after_destroy :delete_screenshot
  # broadcast updates when the layer changed because of default_center + default_zoom
  after_touch :broadcast_update, unless: proc { |record| record.center && record.zoom }
  before_create :create_public_id, :create_layer
  validate :public_id_must_be_unique

  def properties
    { name: name,
      description: description,
      public_id: public_id,
      private: private,
      base_map: get_base_map,
      center: center,
      default_center: default_center,
      zoom: zoom,
      default_zoom: default_zoom,
      pitch: pitch || DEFAULT_PITCH,
      bearing: bearing || DEFAULT_BEARING,
      terrain: terrain || DEFAULT_TERRAIN
    }
  end

  def self.provider_keys
    { mapbox: ENV["MAPBOX_KEY"],
      maptiler: ENV["MAPTILER_KEY"],
      openrouteservice: ENV["OPENROUTESERVICE_KEY"] }
  end

  def create_public_id
    self.public_id = SecureRandom.hex(4).tap { |i| i[0..1] = "11" } unless public_id.present?
  end

  def create_layer
    self.layers << Layer.create!(map: self) unless layers.present?
  end

  def to_json
    { properties: properties, layers: [ to_geojson ] }.to_json
  end

  def to_geojson
    { type: "FeatureCollection",
      features: features.map(&:geojson) }
  end

  def to_gpx
    # https://github.com/hiroaki/ruby-gpx?tab=readme-ov-file#examples
    GPX::GeoJSON.convert_to_gpx(geojson_data: to_geojson.to_json)
  end

  def features
    Feature.in(layer: layers.map(&:id))
  end

  def features_count
    layers.sum(:features_count)
  end

  def public_id_must_be_unique
    # public id must not contain '/'
    errors.add(:public_id, "invalid public id") if public_id =~ /\//
    if Map.where(public_id: public_id).where.not(id: id).exists?
      errors.add(:public_id, "has already been taken")
    end
  end

  def self.create_from_file(path, collection_format: 4326)
    file = File.read(path)
    map_hash = JSON.parse(file)

    map = Map.find_or_create_by(public_id: map_hash["properties"]["public_id"])
    map.update(map_hash["properties"].except("default_center", "default_zoom"))
    map.layers.delete_all
    map.create_layer
    map.layers.first.update!(features: Feature.from_collection(map_hash["layers"][0],
collection_format: collection_format))

    Rails.logger.info "Created map with #{map.features.size} features from #{path}"
    Rails.logger.info "Public id: #{map.public_id}, private id: #{map.id}"
    map
  end

  def screenshot
    "/previews/#{safe_public_id}.jpg?#{updated_at.to_i}" if File.exist?(screenshot_file)
  end

  def screenshot_file
    Rails.root.join("public/previews/#{safe_public_id}.jpg").to_s
  end

  private

  def all_points
    coordinates = features.map { |feature| feature.coordinates(include_height: false) }
    coordinates.flatten.each_slice(2).to_a
  end

  def default_center
    if features.present?
      # setting center to average of all coordinates
      coordinates = all_points
      average_latitude = coordinates.map(&:first).reduce(:+) / coordinates.size.to_f
      average_longitude = coordinates.map(&:last).reduce(:+) / coordinates.size.to_f
      [ average_latitude, average_longitude ]
    else
     DEFAULT_CENTER
    end
  end

  def default_zoom
    if features.present?
      point1 = RGeo::Geographic.spherical_factory.point(all_points.map(&:first).max, all_points.map(&:last).max)
      point2 = RGeo::Geographic.spherical_factory.point(all_points.map(&:first).min, all_points.map(&:last).min)
      distance_km = point1.distance(point2) / 1000
      Rails.logger.info("Map feature distance: #{distance_km} km")
      case distance_km
      when 0 then DEFAULT_ZOOM
      when 0..1 then 16
      when 1..4 then 14
      when 4..10 then 12
      when 10..50 then 10
      when 50..100 then 9
      when 100..200 then 8
      when 200..1000 then 6
      when 1000..2000 then 4
      else 2
      end
    else
     DEFAULT_ZOOM
    end
  end

  def get_base_map
    if MAPTILER_MAPS.include?(base_map)
      return base_map if ENV["MAPTILER_KEY"].present?
      logger.warn("Cannot use maptiler map #{base_map} without MAPTILER_KEY. Falling back to: #{default_base_map}")
      return default_base_map
    elsif (BASE_MAPS + OPENFREE_MAPS + VERSATILES_MAPS).include?(base_map) || base_map == "test"
      return base_map
    end
    logger.warn("Map '#{base_map}' not found, falling back to #{default_base_map}")
    default_base_map
  end

  def default_base_map
    ENV["DEFAULT_MAP"] || "osmRasterTiles"
  end

  def broadcast_update
    # broadcast to private + public channel
    [ id, public_id ].each do |id|
      ActionCable.server.broadcast("map_channel_#{id}",
                                   { event: "update_map", map: properties.as_json })
    end
  end

  def delete_screenshot
    File.delete(screenshot_file) if File.exist?(screenshot_file)
  end

  def safe_public_id
    public_id.gsub(/\/|\.\./, "_")
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_global_js_values, only: %i[show]
  before_action :set_map, only: %i[show properties destroy]
  before_action :require_login, only: %i[my]
  before_action :require_map_owner, only: %i[destroy]

  layout "map", only: [ :show ]

  def index
    @maps = Map.where.not(private: true).includes(:layers, :user).order(updated_at: :desc)
  end

  def my
    @maps = Map.where(user: @user).includes(:layers, :user).order(updated_at: :desc)
  end

  def show
    if request.format.html?
      @map_properties = @map.properties
      gon.map_id = params[:id]
      gon.map_mode = (params[:id] == @map.id.to_s) ? "rw" : "ro"
      gon.map_mode = "static" if params["static"]
      @map_mode = gon.map_mode
      gon.csrf_token = form_authenticity_token
      gon.map_properties = @map_properties
    end

    respond_to do |format|
      format.html do
        case params["engine"]
        when "deck"
          render "deck"
        else
          render "maplibre"
        end
      end
      format.json { render json: @map.to_json }
      format.geojson { render json: @map.to_geojson }
      format.gpx { send_data @map.to_gpx, filename: @map.public_id + ".gpx" }
    end
  end

  def create
    @map = Map.create!(map_params)
    @map.update(user: @user)

    redirect_to map_url(@map), notice: "Map was successfully created."
  end

  # :nocov:
  def properties
    render json: @map.properties.as_json
  end
  # :nocov:

  # some maplibre style tries to load eg. /atm_11; catching those calls here
  # :nocov:
  def catchall
    head :ok
  end
  # :nocov:

  # Turbo sends the DELETE request automatically with Content-Type: text/vnd.turbo-stream.html
  # We can return a turbo stream command that removes the map element in place
  # To avoid turbo_stream response, force format :html
  def destroy
    @map.destroy!
    # there is an additional broadcast from the model, for the admin page
    render turbo_stream: turbo_stream.remove(@map)
  end

  private

  def require_map_owner
    redirect_to maps_path unless @user&.admin? || (@map.user && @map.user == @user)
  end

  def set_global_js_values
    gon.map_keys = Map.provider_keys
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_map
    @map = Map.includes(:layers, :user)
    @map = @map.find_by(public_id: params[:id]) || @map.find_by(id: params[:id])
    head :not_found unless @map
  end

  # Only allow a list of trusted parameters through.
  def map_params
    params.fetch(:map, {})
  end
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_layers_modal_maplibre.haml
#layers-modal.map-modal{'data-controller': "maplibre"}
  %h2 Layers

  #default-layer
    %h4.layer-name Default Layer
    %input#fileInput{ type: "file" }
    %button{ data: { action: "click->maplibre#upload" } }
      Import gpx/kml
    %ul.layer-elements

app/views/maps/_map.html.haml
- rw = local_assigns[:rw] || false
- avatar = local_assigns[:avatar] || false
- delete = local_assigns[:delete] || false
- last_change = local_assigns[:last_change] || false

.flex-item.map-preview.background-bright{id: dom_id(map)}

  - if map.private
    .map-auth{title: 'This map is private and not linked from the public listing.'}
      %i.bi.bi-lock-fill

  - if map.user && avatar
    -if map.user.image
      = image_tag map.user.image, class: 'map-avatar', loading: 'lazy', alt: ""

  - if delete
    = link_to destroy_map_path(id: map.id), data: { turbo_method: :delete, turbo_confirm: "Do you really want to delete this map?" }, title: 'Delete map', class: 'map-delete' do
      %i.bi.bi-trash

  = link_to(map_path(id: (rw ? map.id : map.public_id)), 'aria-label': "Open map '#{map.name}'") do
    - if map.screenshot
      %img{src: map.screenshot,
           class: 'preview-image',
           loading: 'lazy',
           alt: "Map '#{map.name}'"}
    - else
      = image_tag "preview.png", class: 'preview-image', loading: 'lazy', alt: "Map '#{map.name}'"
    .map-preview-title= map.name

  - if last_change
    %i= "last change #{distance_of_time_in_words(DateTime.now, map.updated_at)} ago"
    %br
    - # Use to_a here to avoid additional db query. Mongoid always runs a query to sum()
    = "#{ map.layers.to_a.sum(&:features_count) } features"
    %br
    = "#{map.images_count} images"
    %br
    public id:
    = link_to map.public_id, map_path(id: map.public_id)

app/views/maps/_map_modal_maplibre.haml
#map-modal.map-modal{'data-controller': "maplibre"}
  %h2 Configure Map
  %label{ for: "map-name"} Name:
  %br
  %input#map-name{type: "text", size: 27}
  %br
  %label{for: "map-baselayer"} Base Map:
  %br
  - Map::BASE_MAPS.each do |base_map|
    - active = (@map.properties[:base_map] == base_map)
    = image_tag("base_maps/#{base_map}.jpg", data: { layer: base_map, action: "click->maplibre#update_basemap"},
                class: "layer-preview #{"active" if active}")
  - if ENV['MAPTILER_KEY']
    - Map::MAPTILER_MAPS.each do |base_map|
      - active = (@map.properties[:base_map] == base_map)
      = image_tag("base_maps/#{base_map}.jpg", data: { layer: base_map, action: "click->maplibre#update_basemap"}, class: "layer-preview #{"active" if active}")
  %br
  Center:
  %span#map-center
    = @map.properties[:center].join(', ')
    %i#map-center-current
  %br
  Zoom:
  %span#map-zoom
    = @map.properties[:zoom]
    %i#map-zoom-current
  %br
  Pitch:
  %span#map-pitch
    = "#{@map.properties[:pitch]}°"
    %i#map-pitch-current
  %br
  %span
    %label{ for: "map-terrain"} Terrain:
    %input#map-terrain{type: "checkbox", checked: @map.properties[:terrain],      data: { action: "click->maplibre#update_terrain"} }
  %br
  %a#set-map-center{href: '#', data: { action: "click->maplibre#update_mapdata" } } Set initial map view to current center/zoom/pitch

app/views/maps/_share_modal.html.haml
#share-modal.map-modal{'data-controller': "map"}
  %h2 Share Map

  %ul
    %li= link_to 'Viewer link', map_path(id: @map.public_id)
    %li= link_to 'Edit link', map_path(@map)
    %li= link_to 'Download geojson', map_features_path(@map.public_id)
    %li= link_to 'Download map export', map_path(id: @map.public_id, format: :json)

app/views/maps/_status.haml
#status-container
  #status-message
    Message

app/views/maps/deck.haml
= javascript_include_tag "https://unpkg.com/deck.gl/dist.min.js"
= javascript_import_module_tag "deck"

#deck-map.map

app/views/maps/index.html.haml
- content_for :title, "Mapforge: Explore maps"

= turbo_stream_from "public_maps_list"

#maps.flex-container
  - @maps.each do |map|
    = render map, rw: false, last_change: false, avatar: false, delete: false

app/views/maps/list.html.haml
%h1
  Mapforge


#maps.flex-container
  - @maps.each do |map|
    = render map

= link_to "New map", new_map_path

%hr

= link_to 'Contact', 'tom@digitalflow.de'

= link_to 'Github', 'https://github.com/digitaltom/mapforge'

app/views/maps/maplibre.haml
- # https://turfjs.org/
= javascript_include_tag "https://unpkg.com/@turf/turf@6/turf.min.js"

= javascript_include_tag "https://unpkg.com/@mapbox/togeojson"

- # https://github.com/Ionaru/easy-markdown-editor
= javascript_include_tag "https://unpkg.com/easymde/dist/easymde.min.js"

- content_for :title, "Mapforge: #{(@map.name.presence || @map.id)}"
- content_for :head do
  - if @map.screenshot
    %meta{ 'og:image': "#{request.protocol}#{request.host_with_port}#{@map.screenshot}" }


#preloader
  %img.mapforge-logo{ src: "/icons/mapforge-logo-header_white.png", alt: "Logo" }

#map-head.dark-shadow{ title: "Toggle Navigation", data: { 'controller': "map", 'action': "click->map#toggleNavigation", 'toggle': "tooltip", 'bs-placement': "bottom", 'bs-custom-class': 'maplibregl-ctrl-tooltip' } }
  %i#map-nav-toggle.bi.bi-caret-down.ms-2.me-2
  #map-title

#maplibre-map.map.hidden

- unless @map_mode == 'static'
  = render 'status'
  = render 'maps/modals/settings' if @map_mode == 'rw'
  = render 'maps/modals/layers'
  = render 'maps/modals/share'
  = render 'maps/modals/feature'

#dropdown-space

app/views/maps/my.haml
- content_for :title, "Mapforge: My maps"

#maps.flex-container
  - @maps.each do |map|
    = render map, rw: true, last_change: false, avatar: false, delete: true

- if @maps.empty?
  .container.pt-4.mt-4.mb-4.empty-map-list.background-bright
    %p.text-center
      In this gallery, your maps will be shown.
      %br
      You can browse maps of other users via the 'Explore' link, or
      you can start with your first map by clicking on the "Create Map" button above.