config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  ID_PATTERN = /[^\/]+/ # all characters but '/'

  # login routes
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/developer/login", to: "sessions#new"
  post "auth/developer/login", to: "sessions#developer" if Rails.env.local?
  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#logout"

  # some maplibre style tries to load eg. /atm_11; catching those calls here
  get "/:map_resource" => "maps#catchall", as: :catchall, constraints: { map_resource: /[a-z]+_11/ }
  get "/m/:map_resource" => "maps#catchall", constraints: { map_resource: /[a-z]+_11/ }

  scope "/m" do
    get "", to: "maps#index", as: "maps"
    get "/", to: "maps#index"

    # map exports
    get "/:id.json" => "maps#show", constraints: { id: ID_PATTERN }, defaults: { format: "json" }
    get "/:id.geojson" => "maps#show", constraints: { id: ID_PATTERN }, defaults: { format: "geojson" }
    get "/:id.gpx" => "maps#show", constraints: { id: ID_PATTERN }, defaults: { format: "gpx" }
    get "/:id/properties" => "maps#properties", as: :map_properties, constraints: { id: ID_PATTERN }
    get "/:id" => "maps#show", as: :map, format: :html, constraints: { id: ID_PATTERN }

    post "" => "maps#create", as: :create_map
    delete "/:id" => "maps#destroy", as: :destroy_map, constraints: { id: ID_PATTERN }
  end
  get "/my" => "maps#my", as: "my"

  get "/d/:id" => "maps#show", defaults: { engine: "deck" }, as: :deck, constraints: { id: ID_PATTERN }

  get "/admin" => "admin#index"

  # map icons
  get "/icon/:public_id", to: "images#icon", as: "icon", constraints: { public_id: ID_PATTERN }
  get "/image/:public_id", to: "images#image", as: "image", constraints: { public_id: ID_PATTERN }
  post "/images", to: "images#upload", as: "upload"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "frontpage#index"
  get "/frontpage" => "frontpage#index"

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  mount Ulogger::Engine, at: "/ulogger"
end

app/views/shared/_footer.html.haml
%footer#footer.footer.light-background
  .footer-top
    .container
      .row.gy-4
        - # empty block on the left on lg screen
        - # screen < sm, contact moves below links
        .col-lg-5.col-0.footer-about.d-none.d-lg-block

        .col-lg-2.col-sm-4.col-6.footer-links.footer-links-left.mb-sm-2
          %h3.mapforge-font.white-shadow Docs
          %ul
            %li
              %a{ href: "https://github.com/mapforge-org/mapforge/blob/main/README.md" }
                %i.bi.bi-file-text.me-1>
                Readme
            %li
              %a{ href: "https://github.com/mapforge-org/mapforge/blob/main/CHANGELOG.md" }
                %i.bi.bi-file-text.me-1>
                Changelog
            %li
              %a{ href: "https://github.com/mapforge-org/mapforge/blob/main/docs/geojson.md" }
                %i.bi.bi-file-text.me-1>
                Style spec
            %li
              %a{ href: "https://github.com/mapforge-org/mapforge/blob/main/engines/ulogger/README.md" }
                %i.bi.bi-file-text.me-1>
                µlogger API
        .col-lg-2.col-sm-4.col-6.footer-links
          %h3.mapforge-font.white-shadow Project
          %ul
            %li
              %a{ href: "https://github.com/mapforge-org/mapforge/" }
                %i.bi.bi-github.me-1>
                Github
            %li
              %a{ href: "https://github.com/mapforge-org/mapforge/issues" }
                %i.bi.bi-github.me-1>
                Report issue
        .col-lg-3.col-sm-4.mx-auto.footer-links.footer-links-about.text-center.text-sm-start.text-md-start.mb-2
          %div
            %h3.mapforge-font.white-shadow About
            %ul
              %li
                .text-nowrap
                  %strong
                    %i.bi.bi-envelope.me-1
                  %span mapforge@digitalflow.de
              %li
                %a{ href: "https://github.com/digitaltom/mapforge/blob/main/docs/terms.md" }
                  %i.bi.bi-file-text.me-1>
                  Terms of Use
              %li
                %a{ href: "https://github.com/digitaltom/mapforge/blob/main/docs/privacy.md" }
                  %i.bi.bi-file-text.me-1>
                  Privacy Policy

app/views/shared/_header.html.haml
%nav.navbar.navbar-expand-sm.navbar-light.background-bright{class: "#{'fixed-top' if static}"}
  .container-fluid
    %a.navbar-brand{href: '/'}
      %img.mapforge-logo{ src: "/icons/mapforge-logo-header_white.png", alt: "Logo" }
      .mapforge-font.white-shadow{ href: "#" } Mapforge

    %button.navbar-toggler{ type: "button", "data-bs-toggle": "collapse", "data-bs-target": "#navbarSupportedContent", "aria-controls": "navbarSupportedContent", "aria-expanded": "false", "aria-label": "Toggle navigation" }
      %span.navbar-toggler-icon

    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-0.mt-1
        - if menu
          %li.nav-item
            %a.nav-link{ "aria-current": "page", href: maps_path }
              Explore

      - if create_button
        = link_to create_map_path, { class: 'me-4 btn btn-orange btn-create-map', data: { turbo_method: :post } } do
          %i.bi.bi-plus-square
          Create map

    - if @user
      .dropdown.profile-dropdown

        %a.dropdown-toggle{ href: "#", id: "navbarDropdown", role: "button", "data-bs-toggle": "dropdown", "aria-expanded": "false" }<
          - if @user.image
            %img.profile-image{ src: @user.image, alt: '', title: @user.email }
          - else
            %i.profile-image.fs-4.bi.bi-person-circle
        %ul.dropdown-menu{ "aria-labelledby": "navbarDropdown" }
          - if @user.admin?
            %li
              %a.dropdown-item{ href: "/admin" }
                %i.bi.bi-person-workspace
                Admin
          %li
            = link_to my_path, { class: 'dropdown-item' } do
              %i.bi.bi-map
              = "Your maps (#{@user.maps_count})"
          %li
            = link_to logout_path, { class: 'dropdown-item', data: { turbo: false } } do
              %i.bi.bi-box-arrow-in-left
              Logout
    - else
      = link_to login_path, { class: 'login-link' } do
        %i.bi.bi-person-circle
        Login